Iter25
Karinka-malinka/URL_shortener pull request #26
Opened 2024-05-31 12:05 UTC by Karinka-malinka

2024-06-01 22:30 UTC, Bazys commented on grps/server/controller/user/user.go
> +func (u *UsersServer) UserURLs(ctx context.Context, in *emptypb.Empty) (*pb.UserURLsResponse, error) {
Параметр функции, названный `in`, не используется в теле функции. В Go, если определили параметр в функции, но не использовали его внутри, это считается неоптимальным стилем, поскольку параметр занимает место в сигнатуре функции и может сбивать с толку при чтении кода.
В данном случае, есть два возможных решения:
1. **Удаление параметра:** Если параметр `in` действительно не нужен для работы функции, его можно просто удалить из сигнатуры функции. Это делает код чище и проще для понимания.
2. **Переименование в `_`:** Если параметр не используется, но его наличие обязательно по какой-то причине (например, для соответствия интерфейсу или для использования в будущем), его можно переименовать в `_`. В Go, символ `_` используется для игнорирования переменной. Переменные, именованные как `_`, не обязаны быть использованы, т.е. не будет копирования неиспользуемого значения внутрь функции. Это позволяет сохранить сигнатуру функции неизменной, но явно указывает на то, что данный параметр в настоящее время не используется и избежать лишнего использования памяти.

2024-06-01 22:33 UTC, Bazys commented on grps/server/main.go
> +	"github.com/URL_shortener/cmd/config"
импроты не отсортированы!
подключи goimports на гит-хук либо на сохранение файла в IDE

2024-06-01 22:34 UTC, Bazys commented on grps/server/flag.go
> +		cfg.GetConfig(configFile)
а ошибку обраротать?

2024-06-01 22:40 UTC, Bazys requested changes
1. Очень часто забываешь обрабатывать ошибкт. Подключи линтер errcheck
2. Я как то умудрился пропустить прошлый раз факт того что ты ожидаешь ошибку от анонимной функции, запущенной в горутине.
3. goimports или даже gofumpt - импорты должны быть отсортированы

2024-06-03 06:47 UTC, Karinka-malinka commented on grps/server/flag.go
> +		cfg.GetConfig(configFile)
обработала

2024-06-03 06:48 UTC, Karinka-malinka commented on grps/server/main.go
> +	"github.com/URL_shortener/cmd/config"
на сохранение в IDE подключено, но почему-то именно в данном пакете не сработало, видимо из-за pb. Убрала и все отсортировалось

2024-06-03 06:49 UTC, Karinka-malinka commented on grps/server/controller/user/user.go
> +func (u *UsersServer) UserURLs(ctx context.Context, in *emptypb.Empty) (*pb.UserURLsResponse, error) {
поправила, наличие параметра обязательно для сохранения сигнатуры определения функции сервиса grps

2024-06-04 12:07 UTC, Bazys approved these changes

2024-06-10 07:02 UTC, merged